package com.binance.api.client.domain;

public enum UniversalTransferType {
    MAIN_MARGIN,
    UMFUTURE_MARGIN,
    CMFUTURE_MARGIN,
    MARGIN_UMFUTURE,
    MARGIN_CMFUTURE,
    ISOLATEDMARGIN_MARGIN,
    MARGIN_ISOLATEDMARGIN,
    ISOLATEDMARGIN_ISOLATEDMARGIN,
    MAIN_FUNDING,
    FUNDING_MAIN,
    FUNDING_UMFUTURE,
    UMFUTURE_FUNDING,
    MARGIN_FUNDING,
    FUNDING_MARGIN,
    FUNDING_CMFUTURE,
    CMFUTURE_FUNDING,
    MARGIN_MAIN;
}
